### ISSUE TITLE
Note Modify --Rails

### ISSUE THREAD

**Issue by Blacklotus45** [Blacklotus45/INote#18]
Giriş yapmış bir kullanıcıdan var olan bir mesaj idsi alınırsa bu mesajın veri tabanındaki içeriğin yeni içerik ile değiştirilmesi beklenir.

Login yapmış bir kullanıcı
Değişiklik yaptığı mesajın idsi ve yeni içeriği gönderdiğinde
Veri tabanındaki eski entry updatelenir.

not olarak aynı kullanıcının iki farklı cihazdan peş peşe farklı yeni içerik göndermesi göz ardı edilmiştir.

**Comment by tolunayg** [comment]
Notların modifiye edilebilmesi özelliği eklendi.
